### ISSUE TITLE
Zero-shot performances on ScanQA with Vicuna-7B

### ISSUE THREAD

**Issue by UnderTheMangoTree** [OpenGVLab/LAMM#44]
Thanks for your work! I have used the official code with Vicuna-7B under 4 NVIDIA 3090. For the limitations of memory, i used the train_ds3.yaml, and changed the train_micro_batch_size_per_gpu to 1 and gradient_accumulation_steps to 16.
However, the zero-shot performance of the trained model just 0.06570080862533692 on ScanQA. It is far lower than LAMM with vicuna-13, 26.54, which you published in the paper.

I would like to ask the performance of LAMM with Vicuna-7B you tested on various 3D_Benchmark, and the details of training process.
Thank you very much 😁!

**Comment by wangjiongw** [comment]
I will close this issue due to long-term inactivation. Please reopen it if necessary.
