### ISSUE TITLE
Could you provide LLaVA-v1.5 7b/13b results on ChEF leaderboard?

### ISSUE THREAD

**Issue by YuqiHUO** [OpenGVLab/LAMM#53]
Hi, I think ChEF is a great framework for evaluate large multi-modal LLM's. The result of LLaVA you provided in raw paper is LLaVA-1.0-mpt, which is a outdate version. I am curious to find out how does the latest LLaVA models perform in your framework, could you provide some result? Thanks!

**Comment by Coach257** [comment]
We provide a new [leaderboard](https://openlamm.github.io/ch3ef/leaderboard.html) where LLaVA-v1.5 is evaluated. You can check our new work C $h^3$ Ef for more details [link here](https://openlamm.github.io/ch3ef/).
