### ISSUE TITLE
omnibenchmark dataset

### ISSUE THREAD

**Issue by sunwhw** [OpenGVLab/LAMM#59]
<img width="764" alt="image" src="https://github.com/OpenGVLab/LAMM/assets/48038000/431c3647-5e6b-4743-beba-5573b5e00385"> 
Is the above tips for generating the omnibenchmark dataset correct? In addition, can you give the detailed settings involved in generating the omnibenchmark dataset? Or can you update the data download link because your link on the github project is "404"?

**Comment by Coach257** [comment]
Yes, we have uploaded this file.
