### ISSUE TITLE
Is ScicenQA's meta filename mismatched？

### ISSUE THREAD

**Issue by sunwhw** [OpenGVLab/LAMM#63]
ScicenQA's meta filename does not match the link you specified on the website
<img width="914" alt="image" src="https://github.com/OpenGVLab/LAMM/assets/48038000/79912f1e-27da-4a48-acfe-8210e495f83b">

<img width="698" alt="image" src="https://github.com/OpenGVLab/LAMM/assets/48038000/14b40216-5eb9-4f7c-870a-de625d1481f3">

**Comment by Coach257** [comment]
Yes，you can simply fix this by renaming the filename. Sorry for the mistake.
