### ISSUE TITLE
Some benchmarks are missing from the leaderboards

### ISSUE THREAD

**Issue by zhimin-z** [OpenGVLab/LAMM#64]
The claimed supportive tasks fail to show in the leaderboards...
![image](https://github.com/OpenGVLab/LAMM/assets/8592144/ff8e53d4-c4cd-49ab-9919-7d19b861b44a)
![image](https://github.com/OpenGVLab/LAMM/assets/8592144/c8934d44-3671-4d95-86fe-71c65f83f257)

**Comment by zhimin-z** [comment]
Are the benchmarks supported by LAMM and ChEF different by design? @shepnerd @orashi @double125 @yinzhenfei

**Comment by zhimin-z** [comment]
Any update?

**Comment by Coach257** [comment]
Sorry for the late response. ChEF did not design any evaluation pipeline for 3D benchmark. Please refer to [LAMM](https://arxiv.org/pdf/2306.06687.pdf) paper for 3D leaderboard. We will update the 3D leaderboard on the website sooner. Thanks for your feedback.

**Comment by zhimin-z** [comment]
> Sorry for the late response. ChEF did not design any evaluation pipeline for 3D benchmark. Please refer to [LAMM](https://arxiv.org/pdf/2306.06687.pdf) paper for 3D leaderboard. We will update the 3D leaderboard on the website sooner. Thanks for your feedback.

Thanks, what datasets are supported in CheF, only those appearing in the official leaderboards?

**Comment by Coach257** [comment]
Yes, and you can also add other datasets for evaluation in the dataset class.

**Comment by zhimin-z** [comment]
> Yes, and you can also add other datasets for evaluation in the dataset class.

Is there a comprehensive list of the supported benchmarks in CHeF?

**Comment by Coach257** [comment]
As should in the leaderboard, the supported benchmarks are MME, SeedBench and MMBench. The supported datasets are CIFAR, Flickr, VOC, Omnibenchmark , FSC147 and ScienceQA.

**Comment by zhimin-z** [comment]
> As should in the leaderboard, the supported benchmarks are MME, SeedBench and MMBench. The supported datasets are CIFAR, Flickr, VOC, Omnibenchmark , FSC147 and ScienceQA.

Thanks for your reply, does ChEF benchmark support [MSCOCO](https://arxiv.org/abs/1405.0312) as well?
![image](https://github.com/OpenGVLab/LAMM/assets/8592144/d45ecd1c-1e47-4865-96cb-9611e62ee1af)

**Comment by Coach257** [comment]
ChEF supports the POPE benchmark, which is built on MSCOCO dataset. You can refer to [Evaluating Object Hallucination in Large Vision-Language Models](https://arxiv.org/abs/2305.10355) for more details.

**Comment by zhimin-z** [comment]
It seems like the whole leaderboard is removed, closed for now.
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/fbd3dd30-a66f-4c0b-b4da-4157e2e84321">
